---
- name: Configuración de MySQL en una máquina virtual
  hosts: all
  vars:
    mysql_user: ian
    mysql_password: ian123
    db_name: parcial2
  become: true
  become_user: root
  tasks:
    - name: Actualizar los paquetes
      apt:
        update_cache: yes
    

    - name: Instalar PyMySQL
      apt:
        name: python3-pymysql
        state: present
      become: true

    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Iniciar servicio MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Check for sync_binlog setting
      community.mysql.mysql_variables:
        variable: sync_binlog
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Crear un nuevo usuario MySQL
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "*.*:ALL"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        column_case_sensitive: false

    - name: Crear una nueva base de datos con el usuario creado
      community.mysql.mysql_db:
        name: parcial
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"

    - name: Copiar datos de muestra a la máquina remota
      copy:
        src: ./dump.sql
        dest: /tmp/dump.sql

    - name: tabla en la base de datos
      community.mysql.mysql_db:
        name: parcial
        state: import
        target: /tmp/dump.sql
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"


